### ISSUE TITLE
Loading tries to create a file

### ISSUE THREAD

**Issue by dashesy** [frejanordsiek/hdf5storage#30] opened 2015-12-24 00:26 UTC
When using `loadmat`  (on an old `.mat` file) I get this error:

    h5py\_objects.pyx in h5py._objects.with_phil.wrapper (C:\aroot\work\h5py\_objects.c:2584)()

    h5py\_objects.pyx in h5py._objects.with_phil.wrapper (C:\aroot\work\h5py\_objects.c:2543)()
    h5py\h5f.pyx in h5py.h5f.create (C:\aroot\work\h5py\h5f.c:1994)()
    IOError: Unable to create file (Unable to open file: name = 'z:\test\test.mat', errno = 17, error message = 'file exists', flags = 15, o_flags = 502)

I wonder why loading a matrix is calling create. It should never try to overwrite a file on read error, because it may be lost.

**Comment by frejanordsiek** [comment] 2015-12-27 13:55
I found the issue. The problem is that loadmat opens the file in the wrong mode (should be ``'r'``). I will fix it and try to get a bugfix release out today.

**Comment by frejanordsiek** [comment] 2015-12-27 14:45
The issue is fixed in the package. The package has been re-uploaded to PyPI as the bugfix release 0.1.11 at https://pypi.python.org/pypi/hdf5storage/0.1.11

The commits are

master: 13210b6a1a7e4290088a9df41e901f67d9a23312 and be544663c5111ab8318ba95626b5f484a5f17a58

0.1.x: e6a58a736a9c83f06f2ea3adafc57bb63deaaeec , 81e9c8e6b1fbe3d90c7c884e5fa7e5c07b2ed0bd , and 48e49760ef36686700919a818434116d45ceb5d5

**Closed** 2016-02-13 17:03 UTC
Labels: bug
