### ISSUE TITLE
Savemat not converting Python types anymore?

### ISSUE THREAD

**Issue by mandelkow** [frejanordsiek/hdf5storage#124] opened 2022-12-16 23:45 UTC
Greetings!

I am using hdf5storage 0.1.16 with Python 3.10 and I am surprised to discover that native Python types like int do not get converted and saved by savemat (anymore). (I am pretty sure this used to work in the past.) Numpy types like np.int32 get saved normally. No errors are thrown. Python variables are just missing when I use loadmat to retrieve.

Can anyone confirm this problem?
Are there any known incompatibilities?

Cheers, Hendrik

**Comment by frejanordsiek** [comment] 2023-01-20 11:47
This looks like it is the same as #122 .

This is fixed in the a06c749 commit on the 0.1.x branch. It is caused by the numpy.asscalar function being deprecated, which prevented reading the value (it was saved, though). I will be pushing a 0.1.19 bugfix release to PyPI shortly.

**Closed by frejanordsiek** 2023-01-20 11:47 UTC
Labels: bug

**Comment by mandelkow** [comment] 2023-01-23 15:28
Much obliged. And thank you for providing this invaluable resource. 
-Hendrik

**Comment by frejanordsiek** [comment] 2023-01-23 15:39
Is it fixed for you now?

**Comment by mandelkow** [comment] 2023-01-24 19:08
Yes it works again. 
1000x thanks!
-Hendrik
