### ISSUE TITLE
Testsuite failure on armhf architecture

### ISSUE THREAD

**Issue by ghisvail** [frejanordsiek/hdf5storage#36] opened 2016-02-24 09:21 UTC
Dear Freja,

I successfully submitted a Debian package for hdf5storage for use by the Debian Science community. Our CI reports successful build and tests on `amd64` but the test suite fails on `armhf` with the following [log](https://tests.reproducible-builds.org/rb-pkg/unstable/armhf/python-hdf5storage.html).

All errors are of the form: `NotImplementedError: Int/long too big to fit into numpy.int64`.

Any ideas what could cause this?

Thanks.

**Comment by frejanordsiek** [comment] 2016-02-24 20:25
Thank you for noticing this and providing the log. Without the log, it would be very difficult to figure this out.

My best guess is that the issue is that the test code is generating a random ``int`` that is too big. In [0.1.x/tests/make_randoms.py](https://github.com/frejanordsiek/hdf5storage/blob/0.1.x/tests/make_randoms.py) (linse 102-103), random ints are made as

``` python
def random_int():
    return random.randint(-(2**63 - 1), 2**63)
```

Now, on Python 2.x, the size of an integer is 64 bits on a 64-bit Python and 32 bits on a 32-bit python. Where as in Python 3.x, integer and long are combined and this isn't an issue. So, if ``armhf`` is 32-bit, then it is working with 32-bit integers. The function is probably producing a ``long`` instead most of the time, one too big to fit inside 32 bits. Then on lines 1399-1412 of [0.1.x/hdf5storage/Marshallers.py](https://github.com/frejanordsiek/hdf5storage/blob/0.1.x/hdf5storage/Marshallers.py)

``` python
if sys.hexversion >= 0x03000000:
    tp = int
    maxint = 2**63
else:
    tp = long
    maxint = sys.maxint
if type(data) == tp:
    if data > maxint or data < -(maxint - 1):
        raise NotImplementedError('Int/long too big to fit ' \
            + 'into numpy.int64.')
    else:
        out = int(data)
else:
    out = data
```

produces an error since ``maxint`` gets set to ``2**31``.

I think I know a fix, but I will need to test it. I think I can get it resolved and get out a new bugfix release Monday.

I haven't had a 32 bit python environment to do tests on in a while. I guess I should fix that soon. When I first saw this issue, my first thought was an endian-ness problem since ``armhf`` is big endian and all the machines I have been testing on are little endian.

**Comment by ghisvail** [comment] 2016-02-25 08:15
Brilliant, thanks for chasing that up. If you are short on time to make a new release, please point me to the commit that fixes this bug and I can make a patch to apply on the existing packaging.

**Comment by frejanordsiek** [comment] 2016-02-26 06:43
I think I have a fix. The fix is in commit 0c95b55. I also changed some test code and added some new tests in a different commit (5f3dd7f) to explicitly test for ``int`` and ``long`` that fit within 32 bits and fit within 64 bits separately.

However, I do not have a 32-bit Python right now to test it (it is going to take me a while to get a 32-bit virtual machine running). Would you be able to test it to see if it fixes the issue.

If this fixes the issue, I will immediately roll out a new release (0.1.13).

**Comment by frejanordsiek** [comment] 2016-02-26 06:50
By the way, I am hoping to roll out a few virtual machines of different architectures (both 32 and 64 bits and both little and big endian) for testing to catch these sorts of bugs easier in the future.

**Comment by ghisvail** [comment] 2016-02-26 10:25
I have applied the 2 commits onto the existing source but it still fails on 32-bit architectures. Please have a look at the build logs for [`i386`](http://debomatic-i386.debian.net/distribution#unstable/python-hdf5storage/0.1.12-3/buildlog) and [`armhf`](http://debomatic-armhf.debian.net/distribution#unstable/python-hdf5storage/0.1.12-3/buildlog).

**Comment by frejanordsiek** [comment] 2016-02-28 12:17
I got a i386 virtual machine going and was able to do a bit of testing. I think I found the problem. It is actually in the test code instead of the main code, for once. It has to do with using ``numpy.array`` to do conversions such as on lines 116 and 202 in [0.1.x/tests/asserts.py](https://github.com/frejanordsiek/hdf5storage/blob/0.1.x/tests/asserts.py). Running the following has different results depending on the

``` python
numpy.array(2**31).dtype
numpy.array(2**60).dtype
```

On 64-bit Python 3.x, the returns are ``dtype('int64')`` and ``dtype('int64')``

On 64-bit Python 2.x, the returns are the same as for 64-bit Python 3.x

On 32-bit Python 3.x, the returns are ``dtype('int32')`` and ``dtype('int64')``

On 32-bit Python 2.x, the returns are the same as for 32-bit Python 2.x


Essentially, on 32-bit Python, Numpy converts ``int`` to either ``numpy.int32`` or ``numpy.int64`` depending on the size. But in 64-bit Python, Numpy always converts it to ``numpy.int64``.

I am going to work on a fix now.

**Comment by frejanordsiek** [comment] 2016-02-28 12:34
I fixed the tests with commit ad4fedf in the 0.1.x branch. I essentially added explicit conversion of ``int`` and ``long`` to ``numpy.int64`` in the testing code when comparing the original data to what was written and then read back (conversion is done to the original data).

It works on both amd64 and i386 as far as I can tell.

I still need to get an armhf virtual machine running on QEMU. Spent all morning trying with no success.

**Comment by ghisvail** [comment] 2016-02-28 14:30
I ran the packaging with commit ad4fedf and both builds (i386 and armhf) now runs successfully. Please consider doing a new official release from the current snapshot. Thanks.

**Comment by frejanordsiek** [comment] 2016-02-29 00:08
Just rolled out the bugfix release (just updated the version strings and the README). It is now up on PyPI at https://pypi.python.org/pypi/hdf5storage/0.1.13

**Closed** 2016-03-25 21:22 UTC
Labels: bug, bug: 32 vs 64 bit issue, bug: Python version issue
